config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new" # The `new` route should be placed before the `show` route
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # Needed to instantiate the form_with
  end

  def create
    @task = Task.new(task_params)
    @task.save;
    # No need for a create.html.erb view
    redirect_to task_path(@task);
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
  <div>
    <input type="checkbox" id="<%= task.title %>" name="<%= task.title %>" <%= task.completed ? "checked" : "" %>>
    <label for="<%= task.title %>"><%= link_to task.title, task_path(task) %></label>
  </div>
<% end %>
<br>
<div><%= link_to "Add a new task", tasks_new_path %></div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<br>
<div><%= link_to 'Back to list', tasks_path %></div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<div>
  <%= @task.details %>
</div>
<div>
  <input type="checkbox" id="<%= @task.title %>" <%= @task.completed ? "checked" : "" %>>
  <label><%= @task.completed ? "This task is completed" : "This task is not completed" %></label>
</div>
<div>
  <p><%= link_to 'Back to the list', tasks_path %></p>
</div>